In [21]:
import numpy as np;
arr_1=np.array([1,2,3])
arr_2=np.array([5,6,7])
new_arr=arr_1+arr_2;
print(new_arr)

menu=np.array(['chese','bbq','veg','spicy'])
print(menu)
print('Shape=',menu.shape)
print('Size',menu.size)
print('Dimension',menu.ndim)
print(menu)
prices=np.array([100,200,300,400])
print(prices*0.30)
list_1=[100,200,30,40]
print(np.array(list_1))
print(np.zeros(list_1))
print(np.zeros((2,3)))


[ 6  8 10]
['chese' 'bbq' 'veg' 'spicy']
Shape= (4,)
Size 4
Dimension 1
['chese' 'bbq' 'veg' 'spicy']
[ 30.  60.  90. 120.]
[100 200  30  40]
[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  ...

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.

In [33]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
np_zeros=np.zeros((2,3))
np_ones=np.ones((2,3))
print(np_zeros+np_ones)

bbq_boxes=np.full((2,3),'rifat')
print(bbq_boxes)
kids__order=np.random.randint(1, 8,(2,3))
print(kids__order)
np_random_order=np.random.randint(1,100,(3,3))
print(np_random_order)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[['rifat' 'rifat' 'rifat']
 ['rifat' 'rifat' 'rifat']]
[[2 3 7]
 [5 6 5]]
[[25 13 60]
 [84 72 34]
 [20 20 92]]


In [ ]:

random__int=np.random.rand(2,3)
print(random__int)

dignoal__matrix=np.identity(3)
print(dignoal__matrix)



[[0.0025266  0.24639832 0.07316667]
 [0.46175649 0.73685216 0.70910611]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
delevary__times=np.arange(0,50,15)
delevary__times=np.arange(0,100,20)
print(delevary__times)
cooking__shift=np.linspace(0,70,100)
print(cooking__shift)
orders=np.array(['chese','veg','spicy','bbq'])
orders=orders[0:1]
print(orders)

[ 0 20 40 60 80]
[ 0.          0.70707071  1.41414141  2.12121212  2.82828283  3.53535354
  4.24242424  4.94949495  5.65656566  6.36363636  7.07070707  7.77777778
  8.48484848  9.19191919  9.8989899  10.60606061 11.31313131 12.02020202
 12.72727273 13.43434343 14.14141414 14.84848485 15.55555556 16.26262626
 16.96969697 17.67676768 18.38383838 19.09090909 19.7979798  20.50505051
 21.21212121 21.91919192 22.62626263 23.33333333 24.04040404 24.74747475
 25.45454545 26.16161616 26.86868687 27.57575758 28.28282828 28.98989899
 29.6969697  30.4040404  31.11111111 31.81818182 32.52525253 33.23232323
 33.93939394 34.64646465 35.35353535 36.06060606 36.76767677 37.47474747
 38.18181818 38.88888889 39.5959596  40.3030303  41.01010101 41.71717172
 42.42424242 43.13131313 43.83838384 44.54545455 45.25252525 45.95959596
 46.66666667 47.37373737 48.08080808 48.78787879 49.49494949 50.2020202
 50.90909091 51.61616162 52.32323232 53.03030303 53.73737374 54.44444444
 55.15151515 55.85858586 56.5656565

In [ ]:
s=np.array(['chese','veg','spicy','bbq'])
print(s[0:2])
print(s[0:1])
print(s[:1])
print(s[::2])
print(s[2:])

['chese' 'veg']
['chese']
['chese']
['chese' 'spicy']
['spicy' 'bbq']


In [ ]:
orders=np.array([
    ['chese','veg'],
    ['spicy','bbq']
]
)
print(orders[0,1])
print(orders[1,0])
print(orders[1,1])
print(orders[0,0])
print(orders[:,0])


veg
spicy
bbq
chese
['chese' 'spicy']
[]


In [96]:
orders=np.array(
    [
        ['chese','veg','veg'],
        ['spicy','bbq','spicy']
    ]
)
print(orders)
print(orders[0][0])
print(orders[0][1])
print(orders[0][2])

print(orders[1][0])
print(orders[1][1])
print(orders[1][2])


print(orders[0,0:1])

[['chese' 'veg' 'veg']
 ['spicy' 'bbq' 'spicy']]
chese
veg
veg
spicy
bbq
spicy
['chese']


In [ ]:
sales=np.array(
 [1000,1500,8000,3500]   
)
print(f'Max sales Index:{np.argmax(sales)}')
print(f'Min sales Index:{np.argmin(sales)}')
print(f'Maximum sales:{max(sales)}')

n=np.array([1,2,3,4,5])
s=0;
for i in n:
    s=s+i;
print(s/3)



Max sales Index:2
Min sales Index:0
Maximum sales:8000
5.0
